apiVersion: apps/v1
kind: Deployment
metadata:
  name: ffmpeg4-processing
  labels: 
    app: ffmpeg4 
    tier: server
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: ffmpeg4 
      tier: server
  template:
    metadata:
      labels:
        app: ffmpeg4 
        tier: server
    spec:
      automountServiceAccountToken: false
      nodeSelector:
        nodePool: worker2
      containers:
      - name: ffmpeg4 
        image: jrottenberg/ffmpeg
        imagePullPolicy: Always
        command: ["ffmpeg", "-i", "udp://127.0.0.1:23000", "-c", "copy", "-flags", "+global_header", "-f", "segment", "-segment_time", "10", "-segment_format_options", "movflags=+faststart", "-reset_timestamps", "1", "/tmp/workdir/video/test%d.mp4"]
        ports:
          - containerPort: 23000
            hostPort: 23000 
        volumeMounts:
          - name: output
            mountPath: /tmp/workdir/video
      hostNetwork: true 
#      dnsPolicy: ClusterFirstWithHostNet
      restartPolicy: Always
      volumes: 
        - name: output
          hostPath:
            path: /output/ffmpeg4
